'use client';

import { useState, useRef, useEffect } from 'react';

interface CodeBlockProps {
  children?: React.ReactNode;
  className?: string;
  /** HTML string generated by Shiki (injected from server) */
  highlightedHtml?: string;
  language?: string;
}

/**
 * Enhanced code block with:
 * - Copy-to-clipboard button
 * - Language label
 * - Mac-style header dots
 * - Better scrolling & styling
 */
export function CodeBlock({
  children,
  className,
  highlightedHtml,
  language,
}: CodeBlockProps) {
  const [copied, setCopied] = useState(false);
  const codeRef = useRef<HTMLPreElement>(null);

  const handleCopy = async () => {
    const text = codeRef.current?.textContent || '';
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
    } catch {
      // fallback: noop
    }
  };

  useEffect(() => {
    if (copied) {
      const t = setTimeout(() => setCopied(false), 2000);
      return () => clearTimeout(t);
    }
  }, [copied]);

  return (
    <div className="code-block-wrapper group relative mb-6 rounded-lg border border-border-default overflow-hidden">
      {/* Header bar */}
      <div className="code-block-header flex items-center justify-between px-4 py-2 border-b border-border-default">
        <div className="flex items-center gap-3">
          {/* Mac-style dots */}
          <div className="flex gap-1.5">
            <span className="w-3 h-3 rounded-full bg-[#ff5f57]" />
            <span className="w-3 h-3 rounded-full bg-[#febc2e]" />
            <span className="w-3 h-3 rounded-full bg-[#28c840]" />
          </div>
          {/* Language label */}
          {language && (
            <span className="text-xs font-mono text-text-muted uppercase tracking-wider">
              {language}
            </span>
          )}
        </div>
        {/* Copy button */}
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 text-xs text-text-muted hover:text-text-primary transition-colors px-2 py-1 rounded hover:bg-border-light"
          aria-label="Copy code"
        >
          {copied ? (
            <>
              <CheckIcon />
              <span>Copied!</span>
            </>
          ) : (
            <>
              <CopyIcon />
              <span className="hidden sm:inline">Copy</span>
            </>
          )}
        </button>
      </div>

      {/* Code content */}
      {highlightedHtml ? (
        <pre
          ref={codeRef}
          className={`code-block-content p-4 overflow-x-auto text-sm leading-relaxed ${className || ''}`}
          dangerouslySetInnerHTML={{ __html: highlightedHtml }}
        />
      ) : (
        <pre
          ref={codeRef}
          className={`code-block-content p-4 overflow-x-auto text-sm leading-relaxed ${className || ''}`}
        >
          {children}
        </pre>
      )}
    </div>
  );
}

function CopyIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
